export type Airport = { iata: string; city: string; name: string; country: string };

// Curated list of ~200 major international airports.
// Falls back to free-text IATA entry if user types a code not in the list.
export const AIRPORTS: Airport[] = [
  // Europe — UK & Ireland
  { iata: "LHR", city: "London", name: "Heathrow", country: "UK" },
  { iata: "LGW", city: "London", name: "Gatwick", country: "UK" },
  { iata: "STN", city: "London", name: "Stansted", country: "UK" },
  { iata: "LTN", city: "London", name: "Luton", country: "UK" },
  { iata: "LCY", city: "London", name: "City", country: "UK" },
  { iata: "MAN", city: "Manchester", name: "Manchester", country: "UK" },
  { iata: "EDI", city: "Edinburgh", name: "Edinburgh", country: "UK" },
  { iata: "GLA", city: "Glasgow", name: "Glasgow", country: "UK" },
  { iata: "BHX", city: "Birmingham", name: "Birmingham", country: "UK" },
  { iata: "BRS", city: "Bristol", name: "Bristol", country: "UK" },
  { iata: "DUB", city: "Dublin", name: "Dublin", country: "Ireland" },
  { iata: "ORK", city: "Cork", name: "Cork", country: "Ireland" },

  // Europe — Germany / Austria / Switzerland
  { iata: "FRA", city: "Frankfurt", name: "Frankfurt", country: "Germany" },
  { iata: "MUC", city: "Munich", name: "Munich", country: "Germany" },
  { iata: "BER", city: "Berlin", name: "Brandenburg", country: "Germany" },
  { iata: "HAM", city: "Hamburg", name: "Hamburg", country: "Germany" },
  { iata: "DUS", city: "Düsseldorf", name: "Düsseldorf", country: "Germany" },
  { iata: "CGN", city: "Cologne", name: "Cologne/Bonn", country: "Germany" },
  { iata: "STR", city: "Stuttgart", name: "Stuttgart", country: "Germany" },
  { iata: "VIE", city: "Vienna", name: "Vienna", country: "Austria" },
  { iata: "SZG", city: "Salzburg", name: "Salzburg", country: "Austria" },
  { iata: "ZRH", city: "Zürich", name: "Zürich", country: "Switzerland" },
  { iata: "GVA", city: "Geneva", name: "Geneva", country: "Switzerland" },
  { iata: "BSL", city: "Basel", name: "EuroAirport", country: "Switzerland" },

  // Europe — France / Benelux
  { iata: "CDG", city: "Paris", name: "Charles de Gaulle", country: "France" },
  { iata: "ORY", city: "Paris", name: "Orly", country: "France" },
  { iata: "NCE", city: "Nice", name: "Côte d'Azur", country: "France" },
  { iata: "LYS", city: "Lyon", name: "Saint-Exupéry", country: "France" },
  { iata: "MRS", city: "Marseille", name: "Provence", country: "France" },
  { iata: "TLS", city: "Toulouse", name: "Blagnac", country: "France" },
  { iata: "BOD", city: "Bordeaux", name: "Bordeaux", country: "France" },
  { iata: "NTE", city: "Nantes", name: "Atlantique", country: "France" },
  { iata: "AMS", city: "Amsterdam", name: "Schiphol", country: "Netherlands" },
  { iata: "RTM", city: "Rotterdam", name: "The Hague", country: "Netherlands" },
  { iata: "BRU", city: "Brussels", name: "Brussels", country: "Belgium" },
  { iata: "CRL", city: "Charleroi", name: "Brussels South", country: "Belgium" },
  { iata: "LUX", city: "Luxembourg", name: "Findel", country: "Luxembourg" },

  // Europe — Iberia & Italy
  { iata: "MAD", city: "Madrid", name: "Barajas", country: "Spain" },
  { iata: "BCN", city: "Barcelona", name: "El Prat", country: "Spain" },
  { iata: "AGP", city: "Málaga", name: "Costa del Sol", country: "Spain" },
  { iata: "PMI", city: "Palma", name: "Palma de Mallorca", country: "Spain" },
  { iata: "VLC", city: "Valencia", name: "Valencia", country: "Spain" },
  { iata: "SVQ", city: "Seville", name: "Seville", country: "Spain" },
  { iata: "BIO", city: "Bilbao", name: "Bilbao", country: "Spain" },
  { iata: "LIS", city: "Lisbon", name: "Humberto Delgado", country: "Portugal" },
  { iata: "OPO", city: "Porto", name: "Porto", country: "Portugal" },
  { iata: "FNC", city: "Funchal", name: "Madeira", country: "Portugal" },
  { iata: "FCO", city: "Rome", name: "Fiumicino", country: "Italy" },
  { iata: "CIA", city: "Rome", name: "Ciampino", country: "Italy" },
  { iata: "MXP", city: "Milan", name: "Malpensa", country: "Italy" },
  { iata: "LIN", city: "Milan", name: "Linate", country: "Italy" },
  { iata: "BGY", city: "Milan", name: "Bergamo", country: "Italy" },
  { iata: "VCE", city: "Venice", name: "Marco Polo", country: "Italy" },
  { iata: "NAP", city: "Naples", name: "Capodichino", country: "Italy" },
  { iata: "FLR", city: "Florence", name: "Peretola", country: "Italy" },
  { iata: "BLQ", city: "Bologna", name: "Bologna", country: "Italy" },
  { iata: "CTA", city: "Catania", name: "Fontanarossa", country: "Italy" },

  // Europe — Nordic & Baltic
  { iata: "CPH", city: "Copenhagen", name: "Kastrup", country: "Denmark" },
  { iata: "ARN", city: "Stockholm", name: "Arlanda", country: "Sweden" },
  { iata: "GOT", city: "Gothenburg", name: "Landvetter", country: "Sweden" },
  { iata: "OSL", city: "Oslo", name: "Gardermoen", country: "Norway" },
  { iata: "BGO", city: "Bergen", name: "Flesland", country: "Norway" },
  { iata: "HEL", city: "Helsinki", name: "Vantaa", country: "Finland" },
  { iata: "KEF", city: "Reykjavik", name: "Keflavík", country: "Iceland" },
  { iata: "TLL", city: "Tallinn", name: "Lennart Meri", country: "Estonia" },
  { iata: "RIX", city: "Riga", name: "Riga", country: "Latvia" },
  { iata: "VNO", city: "Vilnius", name: "Vilnius", country: "Lithuania" },

  // Europe — Eastern & SE
  { iata: "WAW", city: "Warsaw", name: "Chopin", country: "Poland" },
  { iata: "KRK", city: "Kraków", name: "John Paul II", country: "Poland" },
  { iata: "GDN", city: "Gdańsk", name: "Lech Wałęsa", country: "Poland" },
  { iata: "PRG", city: "Prague", name: "Václav Havel", country: "Czechia" },
  { iata: "BUD", city: "Budapest", name: "Ferenc Liszt", country: "Hungary" },
  { iata: "OTP", city: "Bucharest", name: "Henri Coandă", country: "Romania" },
  { iata: "SOF", city: "Sofia", name: "Sofia", country: "Bulgaria" },
  { iata: "ATH", city: "Athens", name: "Eleftherios Venizelos", country: "Greece" },
  { iata: "SKG", city: "Thessaloniki", name: "Macedonia", country: "Greece" },
  { iata: "HER", city: "Heraklion", name: "Nikos Kazantzakis", country: "Greece" },
  { iata: "IST", city: "Istanbul", name: "Istanbul Airport", country: "Turkey" },
  { iata: "SAW", city: "Istanbul", name: "Sabiha Gökçen", country: "Turkey" },
  { iata: "AYT", city: "Antalya", name: "Antalya", country: "Turkey" },
  { iata: "ZAG", city: "Zagreb", name: "Franjo Tuđman", country: "Croatia" },
  { iata: "SPU", city: "Split", name: "Split", country: "Croatia" },
  { iata: "DBV", city: "Dubrovnik", name: "Dubrovnik", country: "Croatia" },
  { iata: "BEG", city: "Belgrade", name: "Nikola Tesla", country: "Serbia" },
  { iata: "LJU", city: "Ljubljana", name: "Jože Pučnik", country: "Slovenia" },

  // North America — US
  { iata: "JFK", city: "New York", name: "JFK", country: "USA" },
  { iata: "LGA", city: "New York", name: "LaGuardia", country: "USA" },
  { iata: "EWR", city: "Newark", name: "Newark Liberty", country: "USA" },
  { iata: "BOS", city: "Boston", name: "Logan", country: "USA" },
  { iata: "DCA", city: "Washington", name: "Reagan National", country: "USA" },
  { iata: "IAD", city: "Washington", name: "Dulles", country: "USA" },
  { iata: "BWI", city: "Baltimore", name: "BWI", country: "USA" },
  { iata: "PHL", city: "Philadelphia", name: "Philadelphia", country: "USA" },
  { iata: "ATL", city: "Atlanta", name: "Hartsfield-Jackson", country: "USA" },
  { iata: "MIA", city: "Miami", name: "Miami", country: "USA" },
  { iata: "MCO", city: "Orlando", name: "Orlando", country: "USA" },
  { iata: "FLL", city: "Fort Lauderdale", name: "Hollywood", country: "USA" },
  { iata: "TPA", city: "Tampa", name: "Tampa", country: "USA" },
  { iata: "CLT", city: "Charlotte", name: "Douglas", country: "USA" },
  { iata: "RDU", city: "Raleigh", name: "Raleigh-Durham", country: "USA" },
  { iata: "ORD", city: "Chicago", name: "O'Hare", country: "USA" },
  { iata: "MDW", city: "Chicago", name: "Midway", country: "USA" },
  { iata: "DTW", city: "Detroit", name: "Metropolitan", country: "USA" },
  { iata: "MSP", city: "Minneapolis", name: "Saint Paul", country: "USA" },
  { iata: "DFW", city: "Dallas", name: "Fort Worth", country: "USA" },
  { iata: "IAH", city: "Houston", name: "Bush", country: "USA" },
  { iata: "AUS", city: "Austin", name: "Bergstrom", country: "USA" },
  { iata: "DEN", city: "Denver", name: "Denver", country: "USA" },
  { iata: "SLC", city: "Salt Lake City", name: "Salt Lake City", country: "USA" },
  { iata: "PHX", city: "Phoenix", name: "Sky Harbor", country: "USA" },
  { iata: "LAS", city: "Las Vegas", name: "Harry Reid", country: "USA" },
  { iata: "LAX", city: "Los Angeles", name: "LAX", country: "USA" },
  { iata: "SAN", city: "San Diego", name: "San Diego", country: "USA" },
  { iata: "SFO", city: "San Francisco", name: "SFO", country: "USA" },
  { iata: "SJC", city: "San Jose", name: "Mineta", country: "USA" },
  { iata: "OAK", city: "Oakland", name: "Oakland", country: "USA" },
  { iata: "PDX", city: "Portland", name: "Portland", country: "USA" },
  { iata: "SEA", city: "Seattle", name: "Sea-Tac", country: "USA" },
  { iata: "HNL", city: "Honolulu", name: "Daniel K. Inouye", country: "USA" },

  // North America — Canada & Mexico
  { iata: "YYZ", city: "Toronto", name: "Pearson", country: "Canada" },
  { iata: "YUL", city: "Montreal", name: "Trudeau", country: "Canada" },
  { iata: "YVR", city: "Vancouver", name: "Vancouver", country: "Canada" },
  { iata: "YYC", city: "Calgary", name: "Calgary", country: "Canada" },
  { iata: "YEG", city: "Edmonton", name: "Edmonton", country: "Canada" },
  { iata: "YOW", city: "Ottawa", name: "Macdonald-Cartier", country: "Canada" },
  { iata: "YHZ", city: "Halifax", name: "Stanfield", country: "Canada" },
  { iata: "MEX", city: "Mexico City", name: "Benito Juárez", country: "Mexico" },
  { iata: "CUN", city: "Cancún", name: "Cancún", country: "Mexico" },
  { iata: "GDL", city: "Guadalajara", name: "Guadalajara", country: "Mexico" },

  // South America
  { iata: "GRU", city: "São Paulo", name: "Guarulhos", country: "Brazil" },
  { iata: "GIG", city: "Rio de Janeiro", name: "Galeão", country: "Brazil" },
  { iata: "BSB", city: "Brasília", name: "Brasília", country: "Brazil" },
  { iata: "EZE", city: "Buenos Aires", name: "Ezeiza", country: "Argentina" },
  { iata: "SCL", city: "Santiago", name: "Arturo Merino", country: "Chile" },
  { iata: "LIM", city: "Lima", name: "Jorge Chávez", country: "Peru" },
  { iata: "BOG", city: "Bogotá", name: "El Dorado", country: "Colombia" },
  { iata: "UIO", city: "Quito", name: "Mariscal Sucre", country: "Ecuador" },
  { iata: "MVD", city: "Montevideo", name: "Carrasco", country: "Uruguay" },

  // Middle East
  { iata: "DXB", city: "Dubai", name: "Dubai International", country: "UAE" },
  { iata: "AUH", city: "Abu Dhabi", name: "Zayed", country: "UAE" },
  { iata: "DOH", city: "Doha", name: "Hamad", country: "Qatar" },
  { iata: "RUH", city: "Riyadh", name: "King Khalid", country: "Saudi Arabia" },
  { iata: "JED", city: "Jeddah", name: "King Abdulaziz", country: "Saudi Arabia" },
  { iata: "TLV", city: "Tel Aviv", name: "Ben Gurion", country: "Israel" },
  { iata: "AMM", city: "Amman", name: "Queen Alia", country: "Jordan" },
  { iata: "BAH", city: "Bahrain", name: "Bahrain", country: "Bahrain" },
  { iata: "KWI", city: "Kuwait", name: "Kuwait", country: "Kuwait" },

  // Asia
  { iata: "HND", city: "Tokyo", name: "Haneda", country: "Japan" },
  { iata: "NRT", city: "Tokyo", name: "Narita", country: "Japan" },
  { iata: "KIX", city: "Osaka", name: "Kansai", country: "Japan" },
  { iata: "NGO", city: "Nagoya", name: "Chubu Centrair", country: "Japan" },
  { iata: "ICN", city: "Seoul", name: "Incheon", country: "South Korea" },
  { iata: "GMP", city: "Seoul", name: "Gimpo", country: "South Korea" },
  { iata: "PEK", city: "Beijing", name: "Capital", country: "China" },
  { iata: "PKX", city: "Beijing", name: "Daxing", country: "China" },
  { iata: "PVG", city: "Shanghai", name: "Pudong", country: "China" },
  { iata: "SHA", city: "Shanghai", name: "Hongqiao", country: "China" },
  { iata: "CAN", city: "Guangzhou", name: "Baiyun", country: "China" },
  { iata: "SZX", city: "Shenzhen", name: "Bao'an", country: "China" },
  { iata: "HKG", city: "Hong Kong", name: "Chek Lap Kok", country: "Hong Kong" },
  { iata: "TPE", city: "Taipei", name: "Taoyuan", country: "Taiwan" },
  { iata: "SIN", city: "Singapore", name: "Changi", country: "Singapore" },
  { iata: "KUL", city: "Kuala Lumpur", name: "KLIA", country: "Malaysia" },
  { iata: "BKK", city: "Bangkok", name: "Suvarnabhumi", country: "Thailand" },
  { iata: "DMK", city: "Bangkok", name: "Don Mueang", country: "Thailand" },
  { iata: "HKT", city: "Phuket", name: "Phuket", country: "Thailand" },
  { iata: "CGK", city: "Jakarta", name: "Soekarno-Hatta", country: "Indonesia" },
  { iata: "DPS", city: "Denpasar", name: "Ngurah Rai (Bali)", country: "Indonesia" },
  { iata: "MNL", city: "Manila", name: "Ninoy Aquino", country: "Philippines" },
  { iata: "HAN", city: "Hanoi", name: "Noi Bai", country: "Vietnam" },
  { iata: "SGN", city: "Ho Chi Minh City", name: "Tan Son Nhat", country: "Vietnam" },
  { iata: "DEL", city: "New Delhi", name: "Indira Gandhi", country: "India" },
  { iata: "BOM", city: "Mumbai", name: "Chhatrapati Shivaji", country: "India" },
  { iata: "BLR", city: "Bengaluru", name: "Kempegowda", country: "India" },
  { iata: "MAA", city: "Chennai", name: "Chennai", country: "India" },
  { iata: "HYD", city: "Hyderabad", name: "Rajiv Gandhi", country: "India" },

  // Africa
  { iata: "CAI", city: "Cairo", name: "Cairo", country: "Egypt" },
  { iata: "JNB", city: "Johannesburg", name: "OR Tambo", country: "South Africa" },
  { iata: "CPT", city: "Cape Town", name: "Cape Town", country: "South Africa" },
  { iata: "NBO", city: "Nairobi", name: "Jomo Kenyatta", country: "Kenya" },
  { iata: "LOS", city: "Lagos", name: "Murtala Muhammed", country: "Nigeria" },
  { iata: "CMN", city: "Casablanca", name: "Mohammed V", country: "Morocco" },
  { iata: "ADD", city: "Addis Ababa", name: "Bole", country: "Ethiopia" },
  { iata: "ALG", city: "Algiers", name: "Houari Boumediene", country: "Algeria" },
  { iata: "TUN", city: "Tunis", name: "Carthage", country: "Tunisia" },

  // Oceania
  { iata: "SYD", city: "Sydney", name: "Kingsford Smith", country: "Australia" },
  { iata: "MEL", city: "Melbourne", name: "Tullamarine", country: "Australia" },
  { iata: "BNE", city: "Brisbane", name: "Brisbane", country: "Australia" },
  { iata: "PER", city: "Perth", name: "Perth", country: "Australia" },
  { iata: "ADL", city: "Adelaide", name: "Adelaide", country: "Australia" },
  { iata: "AKL", city: "Auckland", name: "Auckland", country: "New Zealand" },
  { iata: "WLG", city: "Wellington", name: "Wellington", country: "New Zealand" },
  { iata: "CHC", city: "Christchurch", name: "Christchurch", country: "New Zealand" },
];

export function findAirport(iata: string): Airport | undefined {
  const code = iata.toUpperCase();
  return AIRPORTS.find((a) => a.iata === code);
}
